.github/workflows/ci.yml
Cargo.lock
crates/citeproc/Cargo.toml
crates/citeproc/src/db/mod.rs
crates/citeproc/src/db/test.rs
crates/citeproc/src/lib.rs
crates/db/src/cite.rs
crates/io/src/cite.rs
crates/proc/src/disamb/test.rs
crates/proc/src/test.rs
crates/test-utils/src/humans.rs
crates/test-utils/src/lib.rs
crates/test-utils/src/toml.rs
crates/wasm/js-demo/js/Document.ts
crates/wasm/js-demo/js/DocumentEditor.tsx
crates/wasm/js-demo/js/useDocument.ts
crates/wasm/src/lib.rs

CC @adomasven; Fixes #21, much more discussion there
It seems to work, although the js-demo does not test in-text numbering. Haven't swapped out the serialization strategy yet, but that's not really important. Two things remain:
The main thing is naming -- this is a very difficult method to name. Currently it's `setCompleteDocument`, which is cool except there is no such thing as a Document struct, so I'm unconvinced.
The second is what to do about the existing API (doesn't need to be resolved today). I wouldn't mind actually removing note/inText, and just having sort order technically-undefined-but-some-deterministic-choice until either renumberClusters/setCompleteDocument is called and that cluster gains a position.

Add top-level API to set what clusters appear and in what order

---

crates/citeproc/src/db/mod.rs
crates/citeproc/src/db/test.rs
crates/citeproc/src/lib.rs
crates/db/src/cite.rs
crates/io/src/output/markup.rs
crates/io/src/output/markup/html.rs
crates/proc/src/choose.rs
crates/proc/src/db.rs
crates/proc/src/disamb/mod.rs
crates/proc/src/disamb/ref_context.rs
crates/proc/src/helpers.rs
crates/proc/src/lib.rs
crates/proc/src/sort.rs
crates/proc/src/test.rs
crates/proc/src/walker.rs
crates/test-utils/src/humans.rs
crates/test-utils/src/lib.rs
crates/tools/src/lib.rs
crates/wasm/src/lib.rs

Fixes #28
They probably shouldn't be *quite* this separate, however. The new set_cluster_order interface has more information than before, so you can turn this
> Some paragraph with a forced footnote.`[^1]` But then a normal in-text reference.[@citekey]
>
> `[^1]: @citekey`
into
```rust
db.set_cluster_order(&[
ClusterPosition { id: 1, Some(1) }, // i.e. note 1
ClusterPosition { id: 2, None },    // i.e. in-text reference
]);
```
Resulting in the in-text reference being after a footnote, and hence having `Position::Subsequent` and first-reference-note-number available. But currently that extra intermingling is thrown away.

Treat in-text and note clusters as different streams

---

crates/citeproc/tests/data/ignore.txt
crates/csl/src/lib.rs
crates/csl/src/locale.rs
crates/csl/src/style/mod.rs
crates/csl/src/terms.rs
crates/csl/src/variables.rs
crates/io/src/numeric.rs
crates/io/src/output/markup/html.rs
crates/proc/src/date.rs
crates/proc/src/disamb/implementation.rs
crates/proc/src/element.rs
crates/proc/src/lib.rs
crates/proc/src/number.rs
crates/proc/src/page_range.rs
crates/proc/src/renderer.rs
crates/test-utils/src/lib.rs

Page range formatting, implemented without allocating, using a neat digit-iterator trick from someone on the Rust user forums (credited).
Includes a number of HTML normalisations and style fixes that helped make some of the page-range tests pass.
There are a few unspecified behaviours which don't pass -- mostly weird composite affixed numbers. Mostly the remainder just calls for a slightly more permissive numeric value parser. (E.g. people putting en-dashes in there already, etc.)
1 regression: `csl_test_suite::number_LeadingZeros.txt` as page ranges are now numeric nearly all of the time. Maybe this would be fixed by adding a leading-zeroes count to NumericToken::Num.
```
test result: 1 regressions, 20 new passing tests, 1 new ignores, 19 outputs changed, out of 881 intersecting tests …
```

Page ranges

---

crates/citeproc/tests/data/snapshot.txt
crates/citeproc/tests/snapshots/suite__date_VariousInvalidDates.txt.snap
crates/citeproc/tests/snapshots/suite__flipflop_NumericField.txt.snap
crates/csl/src/locale/lang.rs
crates/io/src/csl_json.rs
crates/io/src/lib.rs
crates/io/src/names.rs
crates/io/src/numeric.rs
crates/io/src/output/markup.rs
crates/io/src/output/markup/flip_flop.rs
crates/io/src/output/markup/html.rs
crates/io/src/output/markup/move_punctuation.rs
crates/io/src/output/markup/parse_quotes.rs
crates/io/src/output/markup/plain.rs
crates/io/src/output/markup/rtf.rs
crates/io/src/output/micro_html.rs
crates/proc/src/date.rs
crates/proc/src/db.rs

- Insert spaces into cite suffixes when they aren't terminated by punctuation
- Smash together more punctuation, more often
- Support `<span class="nodecor">` by removing all formatting for that span
Includes iso language suffixes, VariousinValidDates.

Miscellaneous punctuation

---

crates/wasm/Cargo.toml

This is because --features console triggered it.

Configure wasm-opt to avoid 'exported global cannot be mutable'

---

crates/citeproc/src/api.rs
crates/citeproc/src/lib.rs
crates/citeproc/src/processor.rs
crates/citeproc/src/test.rs
crates/proc/src/db.rs
crates/test-utils/src/humans.rs
crates/test-utils/src/lib.rs
crates/wasm/js-demo/js/Document.ts
crates/wasm/src/lib.rs
crates/wasm/src/utils.rs

Adds a previewCitationCluster API, named after the similar method in citeproc-js.
From the draft README:
---
> ### Preview citation clusters
>
> Sometimes, a user wants to see how a cluster will look while they are editing it, before confirming the change.
> 
> ```javascript
> let cites = [ { id: "citekey", locator: "45" }, { ... } ];
> let positions = [ ... before, { id: 0, note: 34 }, ... after ];
> let preview = driver.previewCitationCluster(cites, positions, "html");
> ```
>
> The positions array is exactly like a call to `setClusterOrder`, except exactly  one of the positions has an id of 0. This could either:
>
> - Replace an existing cluster's position, and preview a cluster replacement; or
> - Represent the position a cluster is hypothetically inserted.
>
> If you passed only one …

Preview citation cluster

---

crates/citeproc/benches/some.rs
crates/cli/src/main.rs
crates/proc/src/disamb/test.rs
crates/proc/src/sort.rs
crates/proc/src/test.rs
crates/test-utils/src/toml.rs
crates/wasm/index.html
crates/wasm/js-demo/js/App.tsx
crates/wasm/js-demo/js/useDocument.ts
crates/wasm/node-tryout/index.js
crates/wasm/src/lib.rs

This was started in #68, it turns out. The terminology is updated to be 
consistent, especially important for uncited items:
- Reset will wipe all refs, replace the list.
- Insert will overwrite if necessary and otherwise insert.

Remove unclear setReferences, replace with insertReferences + resetReferences

---

.github/workflows/ci.yml
crates/citeproc/src/test.rs
crates/io/src/lib.rs
crates/io/src/output/markup/move_punctuation.rs
crates/io/src/output/markup/parse_quotes.rs
crates/proc/src/date.rs
crates/proc/src/disamb/test.rs
crates/proc/src/sort.rs
crates/proc/src/test.rs

- Add cargo test --lib to CI
- Make all the lib tests run (not pass)
- Filter date-parts correctly when producing sort strings
- Finally fix flipflop_Apostrophes.txt and pass all the io tests
Now all the tests do pass, and one new passing integration test came out of it.

Run Rust library test suite as well as integration tests

---

Cargo.lock
crates/csl/Cargo.toml
crates/csl/src/attr.rs
crates/csl/src/error.rs
crates/wasm/Cargo.toml
crates/wasm/src/lib.rs
crates/wasm/src/utils.rs

Fixes #25.
Upgrades roxmltree while we're at it. Minor API change to setStyle(); it now throws rather than returning a perfectly serialized JSON error object.

Throw proper JS errors

---

crates/citeproc/src/api.rs
crates/citeproc/src/lib.rs
crates/citeproc/src/processor.rs
crates/citeproc/src/test.rs
crates/proc/src/disamb/test.rs
crates/proc/src/test.rs
crates/test-utils/src/lib.rs
crates/wasm/README.md
crates/wasm/js-demo/js/App.tsx
crates/wasm/js-demo/js/Document.ts
crates/wasm/js-demo/js/useDocument.ts
crates/wasm/js-tests/index.test.ts
crates/wasm/js-tests/package.json
crates/wasm/js-tests/utils.ts
crates/wasm/js-tests/yarn.lock
crates/wasm/src/lib.rs

- Better typescript for the bibliography APIs
- Add fullRender() which handles draining queue and gives you every rendered 
string in the document.
- Document wasm's bibliography features in the README
- Corrected documentation for batchedUpdates
- Improve and test the bibliography diffing returned from batchedUpdates

Queue-draining fullRender() API; better diffing & bibliography docs

---

.github/workflows/build-wasm.yml
crates/citeproc/src/processor.rs
crates/db/src/lib.rs
crates/wasm/.cargo/config
crates/wasm/Cargo.toml
crates/wasm/scripts/model-package.json
crates/wasm/src/lib.rs

The no-modules build wasn't listed in the package.json's `files` manifest, so it never got published. That was a bit of an oversight. Now you should be able to use it as described in the README.
It also includes some debug info in the published releases, so any stack traces from any panics that occur aren't nonsense, which previously I hadn't been able to get through wasm-opt.
- Preserve debug info through wasm-opt
- Remove `&mut self` from wasm Driver methods so it survives a panic
- Include _no_modules output to NPM package
- Set some better durabilities so salsa can optimize validation

Don't exclude the no-modules target from NPM builds

---

.github/workflows/build-wasm.yml
.github/workflows/ci.yml
README.md
crates/proc/src/lib.rs
crates/wasm/Cargo.toml

Fixes #84, disables wasm-opt so wasm builds are going to be a bit bigger.
MSRV is now 1.43 because of indextree's use of `i16::MIN` and a few other 
packages which are no longer supporting 1.39, I just haven't checked in a 
while. So there we are.

Use Rust 1.43 and fix wasm mutable globals

---

Cargo.lock
crates/wasm/Cargo.toml

See #84
As suggested in https://github.com/rustwasm/wasm-pack/issues/886. This is (probably?) because it's wasm-bindgen & friends that are emitting the mutable globals in question. Context-wise, Zotero runs Firefox ESR 60, which does not support the mutable global import/export WebAssembly feature.

Downgrade to wasm-bindgen 0.2.62

---

crates/wasm/scripts/model-package.json

As usual, I forgot to add the _zotero build to the npm package.json inclusion list.

Actually publish zotero files

---

crates/proc/src/db.rs
crates/proc/src/disamb/test.rs
crates/proc/src/test.rs
crates/wasm/README.md
crates/wasm/js-tests/index.test.ts
crates/wasm/src/lib.rs

Fixes #91, which was never really a bug in the formatting code.
- add test for built_cluster_preview format-changing
* This already passed. Turns out the code was pretty much correct anyway.
- add structure to js-tests, and add an unrecognised output format test to JS
- make previewCitationCluster fail on unknown output format

Error on unrecognised output format (JS)

---

.github/workflows/build-wasm.yml
.github/workflows/ci.yml
crates/wasm/Cargo.toml

Fixes #110
Uses a forked wasm-pack that doesn't use a pinned old wasm-opt version. This was necessary because wasm-opt actually just started segfaulting. I didn't find out what version wasm-pack has it pinned at (from sometime in 2019? 2020?), but downloading wasm-opt from binaryen's GitHub Releases `version_101` works.
Also switches back to -O3 because it's a lot faster to run wasm-opt and the binary is not much bigger.

Fix npm publishing breakage due to wasm-opt segfault

---

crates/citeproc/tests/data/humans/url_csl11_DOI_Affixed_HTTP_Disabled.yml
crates/citeproc/tests/data/humans/url_csl11_DOI_Affixed_HTTP_Prefixed.yml
crates/citeproc/tests/data/humans/url_csl11_PMID_Affixed_HTTP.yml
crates/io/src/output/links.rs
crates/io/src/output/markup.rs
crates/io/src/output/markup/rtf.rs
crates/io/src/output/mod.rs
crates/proc/src/renderer.rs
crates/proc/src/sort/output_format.rs

Fixes #127, fixes #131
- strip url prefix from prefix="... https://doi.org/" (etc)
- internal note, simplifies the OutputFormat API to just take a `Link` and return a `Self::Build`. The list of url-ish variables didn't need to be specific to each OutputFormat implementation (we do only have two, but yeah)
- Fix PMID / PMCID confusion
- match more variants of PMID/PMCID urls
- Confirm doi prefix-stripping works with link_anchors disabled
One note here is that PubMed has started redirecting PMID urls to e.g. <https://pubmed.ncbi.nlm.nih.gov/34706787/>, so that might be a better canonical url format. But for the moment it just does what the csl 1.1 spec says.

Fix doi urls in prefix duplication, and pmids/pmcids

---

.github/workflows/ci.yml
.github/workflows/post-ci.yml
crates/tools/src/lib.rs

Fixes #134 
- don't error when PR submitted by non-collaborator
- post-ci workflow to add a comment on PRs with any regressions included
Example comment, from diffing some random things in my .snapshots folder. Appears from @github-actions [bot]
<details><summary>
Test results (<strong>success</strong>; <a href="https://cormacrelf.github.io/citeproc-rs-test-viewer/branches/master">full results</a>): 24 new passing tests
</summary>
- humans::intext_AuthorOnly_Title.yml
- humans::collapse_YearSuffix_Locator_Ranged.yml
- humans::collapse_YearSuffix_Prefix.yml
- humans::collapse_YearSuffix_Suffix.yml
- fixtures_local::discretionary_SingleNarrativeCitation.txt
- humans::intext_AuthorOnly_DateYearSuffix.yml
- fixtures_local::discretionary_ExampleUnauthored.txt
- …

fix external PR tests

---

crates/citeproc/src/processor.rs
crates/csl/src/lib.rs
crates/csl/src/style/mod.rs

This fixes an issue where bibliography renders with incorrect line spacing.
Struct `style::Bibliography` used `line-spaces`, however it should be `line-spacing` according to [the spec](https://docs.citationstyles.org/en/stable/specification.html#bibliography-specific-options).

Fix "line-spacing" attribute on <bibliography> in CSL is ignored

---

.github/workflows/ci.yml
bindings/xcframework/build.sh
bindings/xcframework/rust-toolchain.toml
crates/citeproc/tests/data/humans/group_TextDateYearSuffix.yml
crates/citeproc/tests/data/humans/group_YearSuffixExplicit.yml
crates/csl/src/style/mod.rs
crates/proc/src/db.rs
crates/proc/src/disamb/implementation.rs
crates/proc/src/disamb/mod.rs
crates/proc/src/disamb/names.rs
crates/proc/src/element.rs
crates/proc/src/group.rs
crates/proc/src/helpers.rs
crates/proc/src/ir.rs
crates/proc/src/ir/transforms.rs
crates/proc/src/names.rs
crates/proc/src/sort.rs
crates/proc/src/tree.rs

As discussed in https://github.com/andras-simonyi/citeproc-el/issues/70#issuecomment-977145690
This makes the "no date" term behave like a variable for group suppression. It also makes the GroupVars code work less by accident and more on purpose.

Solve year-suffix / no-date interaction

---

crates/io/src/csl_json.rs
crates/io/src/names.rs
crates/proc/src/names.rs

This used to use code from citeproc-js, licensed under the Common Public Attribution License, so compliant users of citeproc-rs had to credit Frank, for the small amount of code here and nothing else. It's been a year or two since I've been over it, so I deleted the parts I took, and wrote it again from first principles. It turned out a little bit simpler in general, using just straight ^ and $-based regexes with repetition for given names and last names, rather than the one-particle-at-a-time + given-names-get-reversed strategy of Frank's version.
Also adds support for the using strings and numbers as fuzzy JS-style booleans on the `static-particles` JSON input.

reimplement name parsing

---

crates/citeproc/src/processor.rs
crates/db/src/lib.rs
crates/db/src/xml.rs
crates/wasm/README.md
crates/wasm/js-tests/node/index.test.ts
crates/wasm/scripts/npm-pkg-config.sh
crates/wasm/src/lib.rs
crates/wasm/src/options.rs

setOutputFormat API

---

crates/wasm/README.md
crates/wasm/js-tests/node/index.test.ts
crates/wasm/src/lib.rs

Fixes #119
The overall effect of these commits is to
1. Deprecate previewCitationCluster (using the `@deprecated` JSDoc tag, so TypeScript editors should pick this up and show a warning on use)
2. Add a `previewCluster` that changes the first argument to use an id-less Cluster object, on which you can put a cluster mode, and any future cluster options.
3. Makes the `format` argument optional, because recent wasm-bindgen can do this.
4. Document and test the new stuff, and the deprecated version

previewCitationCluster => previewCluster
